/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1compiladores.gui;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import practica1compiladores.Gramatica;
import practica1compiladores.Produccion;

/**
 *
 * @author pedro
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    DefaultListModel modelo;
    Gramatica gramatica;
    Produccion produccionActual;

    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanelCreacionGramatica = new javax.swing.JPanel();
        jButtonNuevaGramatica = new javax.swing.JButton();
        jScrollPaneGramatica = new javax.swing.JScrollPane();
        jListGramatica = new javax.swing.JList<>();
        jButtonNuevaProduccion = new javax.swing.JButton();
        jLabelNumeroProduccion = new javax.swing.JLabel();
        jButtonNuevoTerminal = new javax.swing.JButton();
        jButtonNuevoSeparador = new javax.swing.JButton();
        jButtonNuevoNoTerminal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneProduccionSeleccionada = new javax.swing.JTextPane();
        jButtonBorrarUltimo = new javax.swing.JButton();
        jButtonSecuenciaNula = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jPanelSimplificacionGramatica = new javax.swing.JPanel();
        jPanelAutomataFinito = new javax.swing.JPanel();
        jPanelReconocimientoHilera = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonNuevaGramatica.setText("Nueva gramatica");
        jButtonNuevaGramatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaGramaticaActionPerformed(evt);
            }
        });

        jListGramatica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListGramaticaMouseClicked(evt);
            }
        });
        jScrollPaneGramatica.setViewportView(jListGramatica);

        jButtonNuevaProduccion.setText("Agregar produccion");
        jButtonNuevaProduccion.setActionCommand("");
        jButtonNuevaProduccion.setEnabled(false);
        jButtonNuevaProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaProduccionActionPerformed(evt);
            }
        });

        jLabelNumeroProduccion.setText("Produccion: ");

        jButtonNuevoTerminal.setText("Nuevo terminal");
        jButtonNuevoTerminal.setEnabled(false);
        jButtonNuevoTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoTerminalActionPerformed(evt);
            }
        });

        jButtonNuevoSeparador.setText("Nuevo separador");
        jButtonNuevoSeparador.setEnabled(false);
        jButtonNuevoSeparador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoSeparadorActionPerformed(evt);
            }
        });

        jButtonNuevoNoTerminal.setText("Nuevo no terminal");
        jButtonNuevoNoTerminal.setEnabled(false);
        jButtonNuevoNoTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoNoTerminalActionPerformed(evt);
            }
        });

        jTextPaneProduccionSeleccionada.setEditable(false);
        jScrollPane1.setViewportView(jTextPaneProduccionSeleccionada);

        jButtonBorrarUltimo.setText("Borrar ultimo");
        jButtonBorrarUltimo.setEnabled(false);
        jButtonBorrarUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUltimoActionPerformed(evt);
            }
        });

        jButtonSecuenciaNula.setText("Secuencia nula");
        jButtonSecuenciaNula.setEnabled(false);
        jButtonSecuenciaNula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecuenciaNulaActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");

        javax.swing.GroupLayout jPanelCreacionGramaticaLayout = new javax.swing.GroupLayout(jPanelCreacionGramatica);
        jPanelCreacionGramatica.setLayout(jPanelCreacionGramaticaLayout);
        jPanelCreacionGramaticaLayout.setHorizontalGroup(
            jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNuevaGramatica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCreacionGramaticaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneGramatica)
                    .addComponent(jButtonNuevaProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCreacionGramaticaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrarUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCreacionGramaticaLayout.createSequentialGroup()
                        .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumeroProduccion)
                            .addGroup(jPanelCreacionGramaticaLayout.createSequentialGroup()
                                .addComponent(jButtonNuevoTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNuevoSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNuevoNoTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSecuenciaNula, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanelCreacionGramaticaLayout.setVerticalGroup(
            jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreacionGramaticaLayout.createSequentialGroup()
                .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCreacionGramaticaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelNumeroProduccion))
                    .addComponent(jButtonGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButtonBorrarUltimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoTerminal)
                    .addComponent(jButtonNuevoSeparador)
                    .addComponent(jButtonNuevoNoTerminal)
                    .addComponent(jButtonSecuenciaNula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNuevaProduccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneGramatica, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNuevaGramatica))
        );

        jTabbedPaneMain.addTab("Creacion gramatica", jPanelCreacionGramatica);

        javax.swing.GroupLayout jPanelSimplificacionGramaticaLayout = new javax.swing.GroupLayout(jPanelSimplificacionGramatica);
        jPanelSimplificacionGramatica.setLayout(jPanelSimplificacionGramaticaLayout);
        jPanelSimplificacionGramaticaLayout.setHorizontalGroup(
            jPanelSimplificacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        jPanelSimplificacionGramaticaLayout.setVerticalGroup(
            jPanelSimplificacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("Simplificacion gramatica", jPanelSimplificacionGramatica);

        javax.swing.GroupLayout jPanelAutomataFinitoLayout = new javax.swing.GroupLayout(jPanelAutomataFinito);
        jPanelAutomataFinito.setLayout(jPanelAutomataFinitoLayout);
        jPanelAutomataFinitoLayout.setHorizontalGroup(
            jPanelAutomataFinitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        jPanelAutomataFinitoLayout.setVerticalGroup(
            jPanelAutomataFinitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("Automata finito", jPanelAutomataFinito);

        javax.swing.GroupLayout jPanelReconocimientoHileraLayout = new javax.swing.GroupLayout(jPanelReconocimientoHilera);
        jPanelReconocimientoHilera.setLayout(jPanelReconocimientoHileraLayout);
        jPanelReconocimientoHileraLayout.setHorizontalGroup(
            jPanelReconocimientoHileraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        jPanelReconocimientoHileraLayout.setVerticalGroup(
            jPanelReconocimientoHileraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("Reconocimiento hilera", jPanelReconocimientoHilera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevaGramaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaGramaticaActionPerformed
        String[] options = {"Nueva gramatica", "Cargar desde Archivo de texto"};
        int seleccion = JOptionPane.showOptionDialog(rootPane,
                "Desea crear una nueva gramatica o cargarla desde un archivo de texto?",
                "Cargar gramatica", WIDTH, HEIGHT, null, options, NORMAL);
        gramatica = new Gramatica();
        modelo = new DefaultListModel();
        if (seleccion == 1) {
            JFileChooser mJFileChooser = new JFileChooser();
            if (mJFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                try {
                    gramatica.leerGramatica(mJFileChooser.getSelectedFile().getPath());
                    jButtonNuevoTerminal.setEnabled(true);
                    jButtonNuevoNoTerminal.setEnabled(true);
                    gramatica.getProducciones().forEach((produccion) -> {
                        modelo.addElement(produccion.toString());
                    });
                    jListGramatica.setModel(modelo);
                } catch (FileNotFoundException ex) {
                }
            }
        } else {
            produccionActual = new Produccion(1);
            jListGramatica.setModel(modelo);
            jButtonNuevoTerminal.setEnabled(true);
            jButtonNuevoNoTerminal.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonNuevaGramaticaActionPerformed

    private void jButtonNuevaProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaProduccionActionPerformed
        try {
            gramatica.getProducciones().add(produccionActual.getId(), produccionActual);
            modelo.add(produccionActual.getId(), produccionActual.toString());
        } catch (Exception e) {
            gramatica.getProducciones().add(produccionActual);
            modelo.addElement(produccionActual.toString());
        }
        jButtonNuevoTerminal.setEnabled(true);
        jButtonNuevoNoTerminal.setEnabled(true);
        produccionActual = new Produccion(gramatica.getProducciones().size() + 1);
        jButtonNuevaProduccion.setEnabled(produccionActual.isCorrect());
    }//GEN-LAST:event_jButtonNuevaProduccionActionPerformed

    private void jButtonNuevoTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoTerminalActionPerformed
        String terminal = JOptionPane.showInputDialog(rootPane, "Inserte el terminal: \n-Solo un caracter\n-letras minusculas o numeros", "Nuevo terminal", JOptionPane.OK_OPTION).substring(0, 1).toLowerCase();
        Pattern pat = Pattern.compile("\\w");
        Matcher mat = pat.matcher(terminal);
        if (mat.matches()) {
            jButtonSecuenciaNula.setEnabled(false);
            produccionActual.addPart(terminal);
            jTextPaneProduccionSeleccionada.setText(produccionActual.toString().substring(produccionActual.toString().indexOf(" ")));
            jButtonNuevaProduccion.setEnabled(produccionActual.isCorrect());
        } else {
            JOptionPane.showMessageDialog(rootPane, "\n-Solo un caracter\n-letras minusculas o numeros", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonNuevoTerminalActionPerformed

    private void jButtonNuevoNoTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoNoTerminalActionPerformed
        jButtonSecuenciaNula.setEnabled(false);
        String noTerminal = "<" + JOptionPane.showInputDialog(rootPane, "Inserte el no terminal", "Nuevo no terminal", JOptionPane.OK_OPTION) + ">";
        produccionActual.addPart(noTerminal);
        jTextPaneProduccionSeleccionada.setText(produccionActual.toString().substring(produccionActual.toString().indexOf(" ")));
        if (produccionActual.isOnRight()) {
            jButtonNuevaProduccion.setEnabled(produccionActual.isCorrect());
        } else {
            jButtonNuevoSeparador.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonNuevoNoTerminalActionPerformed

    private void jListGramaticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListGramaticaMouseClicked
        String produccion = jListGramatica.getSelectedValue();
        jTextPaneProduccionSeleccionada.setText(produccion.substring(produccion.indexOf(" ")));
        jButtonBorrarUltimo.setEnabled(true);
        jLabelNumeroProduccion.setText("Produccion: " + (jListGramatica.getSelectedIndex() + 1));
        produccionActual = gramatica.getProducciones().get(jListGramatica.getSelectedIndex());
    }//GEN-LAST:event_jListGramaticaMouseClicked

    private void jButtonBorrarUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUltimoActionPerformed
        String part = produccionActual.deleteLastPart();
        if (part != null) {
            jTextPaneProduccionSeleccionada.setText(produccionActual.toString().substring(produccionActual.toString().indexOf(" ")));
            if (part.contains("->")) {
                jButtonNuevoSeparador.setEnabled(true);
            }
            if (produccionActual.isSeparator(produccionActual.getPartes().get(produccionActual.getPartes().size()-1))) jButtonSecuenciaNula.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "La produccion esta vacia", "Error", JOptionPane.ERROR_MESSAGE);
        }
        jButtonNuevaProduccion.setEnabled(produccionActual.isCorrect());
    }//GEN-LAST:event_jButtonBorrarUltimoActionPerformed

    private void jButtonNuevoSeparadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoSeparadorActionPerformed
        jButtonNuevoNoTerminal.setEnabled(true);
        jButtonNuevoTerminal.setEnabled(true);
        jButtonSecuenciaNula.setEnabled(true);
        jButtonNuevoSeparador.setEnabled(false);
        produccionActual.addPart(" -> ");
        jTextPaneProduccionSeleccionada.setText(produccionActual.toString().substring(produccionActual.toString().indexOf(" ")));
    }//GEN-LAST:event_jButtonNuevoSeparadorActionPerformed

    private void jButtonSecuenciaNulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecuenciaNulaActionPerformed
        produccionActual.addPart("λ");
        jButtonNuevoNoTerminal.setEnabled(false);
        jButtonNuevoTerminal.setEnabled(false);
        jButtonSecuenciaNula.setEnabled(false);
        jButtonNuevoSeparador.setEnabled(false);
        jButtonNuevaProduccion.setEnabled(produccionActual.isCorrect());
        jButtonBorrarUltimo.setEnabled(true);
        jTextPaneProduccionSeleccionada.setText(produccionActual.toString().substring(produccionActual.toString().indexOf(" ")));
    }//GEN-LAST:event_jButtonSecuenciaNulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarUltimo;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNuevaGramatica;
    private javax.swing.JButton jButtonNuevaProduccion;
    private javax.swing.JButton jButtonNuevoNoTerminal;
    private javax.swing.JButton jButtonNuevoSeparador;
    private javax.swing.JButton jButtonNuevoTerminal;
    private javax.swing.JButton jButtonSecuenciaNula;
    private javax.swing.JLabel jLabelNumeroProduccion;
    private javax.swing.JList<String> jListGramatica;
    private javax.swing.JPanel jPanelAutomataFinito;
    private javax.swing.JPanel jPanelCreacionGramatica;
    private javax.swing.JPanel jPanelReconocimientoHilera;
    private javax.swing.JPanel jPanelSimplificacionGramatica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneGramatica;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTextPane jTextPaneProduccionSeleccionada;
    // End of variables declaration//GEN-END:variables
}
