/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1compiladores;

/**
 *
 * @author pedro
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanelCreacionGramatica = new javax.swing.JPanel();
        jButtonNuevaGramatica = new javax.swing.JButton();
        jScrollPaneGramatica = new javax.swing.JScrollPane();
        jListGramatica = new javax.swing.JList<>();
        jButtonNuevaProduccion = new javax.swing.JButton();
        jLabelNumeroProduccion = new javax.swing.JLabel();
        jButtonNuevoTerminal = new javax.swing.JButton();
        jButtonNuevoSeparador = new javax.swing.JButton();
        jButtonNuevoNoTerminal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jPanelSimplificacionGramatica = new javax.swing.JPanel();
        jPanelAutomataFinito = new javax.swing.JPanel();
        jPanelReconocimientoHilera = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonNuevaGramatica.setText("Crear nueva gramatica");
        jButtonNuevaGramatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaGramaticaActionPerformed(evt);
            }
        });

        jListGramatica.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneGramatica.setViewportView(jListGramatica);

        jButtonNuevaProduccion.setText("Agregar produccion");
        jButtonNuevaProduccion.setActionCommand("");
        jButtonNuevaProduccion.setEnabled(false);
        jButtonNuevaProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaProduccionActionPerformed(evt);
            }
        });

        jLabelNumeroProduccion.setText("Produccion: ");

        jButtonNuevoTerminal.setText("Nuevo terminal");
        jButtonNuevoTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoTerminalActionPerformed(evt);
            }
        });

        jButtonNuevoSeparador.setText("Nuevo separador");
        jButtonNuevoSeparador.setEnabled(false);

        jButtonNuevoNoTerminal.setText("Nuevo no terminal");
        jButtonNuevoNoTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoNoTerminalActionPerformed(evt);
            }
        });

        jTextPane2.setEditable(false);
        jScrollPane1.setViewportView(jTextPane2);

        jButton1.setText("Borrar parte");

        javax.swing.GroupLayout jPanelCreacionGramaticaLayout = new javax.swing.GroupLayout(jPanelCreacionGramatica);
        jPanelCreacionGramatica.setLayout(jPanelCreacionGramaticaLayout);
        jPanelCreacionGramaticaLayout.setHorizontalGroup(
            jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonNuevaGramatica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCreacionGramaticaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneGramatica)
                    .addComponent(jButtonNuevaProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNumeroProduccion)
                    .addGroup(jPanelCreacionGramaticaLayout.createSequentialGroup()
                        .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCreacionGramaticaLayout.createSequentialGroup()
                                .addComponent(jButtonNuevoTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNuevoSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNuevoNoTerminal, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelCreacionGramaticaLayout.setVerticalGroup(
            jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreacionGramaticaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelNumeroProduccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCreacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoTerminal)
                    .addComponent(jButtonNuevoSeparador)
                    .addComponent(jButtonNuevoNoTerminal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNuevaProduccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneGramatica, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNuevaGramatica))
        );

        jTabbedPaneMain.addTab("Creacion gramatica", jPanelCreacionGramatica);

        javax.swing.GroupLayout jPanelSimplificacionGramaticaLayout = new javax.swing.GroupLayout(jPanelSimplificacionGramatica);
        jPanelSimplificacionGramatica.setLayout(jPanelSimplificacionGramaticaLayout);
        jPanelSimplificacionGramaticaLayout.setHorizontalGroup(
            jPanelSimplificacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        jPanelSimplificacionGramaticaLayout.setVerticalGroup(
            jPanelSimplificacionGramaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("Simplificacion gramatica", jPanelSimplificacionGramatica);

        javax.swing.GroupLayout jPanelAutomataFinitoLayout = new javax.swing.GroupLayout(jPanelAutomataFinito);
        jPanelAutomataFinito.setLayout(jPanelAutomataFinitoLayout);
        jPanelAutomataFinitoLayout.setHorizontalGroup(
            jPanelAutomataFinitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        jPanelAutomataFinitoLayout.setVerticalGroup(
            jPanelAutomataFinitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("Automata finito", jPanelAutomataFinito);

        javax.swing.GroupLayout jPanelReconocimientoHileraLayout = new javax.swing.GroupLayout(jPanelReconocimientoHilera);
        jPanelReconocimientoHilera.setLayout(jPanelReconocimientoHileraLayout);
        jPanelReconocimientoHileraLayout.setHorizontalGroup(
            jPanelReconocimientoHileraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        jPanelReconocimientoHileraLayout.setVerticalGroup(
            jPanelReconocimientoHileraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jTabbedPaneMain.addTab("Reconocimiento hilera", jPanelReconocimientoHilera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevaGramaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaGramaticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevaGramaticaActionPerformed

    private void jButtonNuevaProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaProduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevaProduccionActionPerformed

    private void jButtonNuevoTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoTerminalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevoTerminalActionPerformed

    private void jButtonNuevoNoTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoNoTerminalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNuevoNoTerminalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNuevaGramatica;
    private javax.swing.JButton jButtonNuevaProduccion;
    private javax.swing.JButton jButtonNuevoNoTerminal;
    private javax.swing.JButton jButtonNuevoSeparador;
    private javax.swing.JButton jButtonNuevoTerminal;
    private javax.swing.JLabel jLabelNumeroProduccion;
    private javax.swing.JList<String> jListGramatica;
    private javax.swing.JPanel jPanelAutomataFinito;
    private javax.swing.JPanel jPanelCreacionGramatica;
    private javax.swing.JPanel jPanelReconocimientoHilera;
    private javax.swing.JPanel jPanelSimplificacionGramatica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneGramatica;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
